# Generated by Django 4.1.2 on 2022-10-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workevidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevidence',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workevidence',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
