# Generated by Django 4.1.2 on 2022-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workevidence', '0002_alter_worker_first_name_alter_worker_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='card_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
